### ISSUE TITLE
error: Number of input channels should be multiple of 3 but got 4 in function 'getMemoryShapes'

### ISSUE THREAD

**Issue by SlausB** [ORB-HD/deface#32]
Running in docker.

`deface.Dockerfile`:
```
FROM docker.io/ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -yq update && apt-get -yq install \
    software-properties-common \
    python3 \
    python3-pip \
    git \
    cmake pkg-config mesa-utils libglu1-mesa-dev freeglut3-dev mesa-common-dev libglew-dev libglfw3-dev libglm-dev libao-dev libmpg123-dev

RUN pip3 install pip

#RUN pip3 install deface
RUN pip3 install 'git+https://github.com/ORB-HD/deface'

WORKDIR /app
```

`deface.sh`:
```
#!/bin/bash
docker build -f deface.Dockerfile -t deface .
docker run \
    -it \
    --rm \
    -v $(pwd):/app \
    --entrypoint=/bin/bash \
    deface
```

Start container and enter it:
> ./deface.sh

Then run `deface` on `friends.png` image:
```
root@ed084ad5d8a4:/app# deface friends.png 
Input:  friends.png
Output: friends_anonymized.png
[ERROR:0@0.113] global /io/opencv/modules/dnn/src/net_impl.cpp (1168) getLayerShapesRecursively OPENCV/DNN: [Convolution]:(onnx_node_output_0!363): getMemoryShapes() throws exception. inputs=1 outputs=0/1 blobs=1
[ERROR:0@0.113] global /io/opencv/modules/dnn/src/net_impl.cpp (1174) getLayerShapesRecursively     input[0] = [ 1 4 1056 1600 ]
[ERROR:0@0.113] global /io/opencv/modules/dnn/src/net_impl.cpp (1182) getLayerShapesRecursively     blobs[0] = CV_32FC1 [ 32 3 3 3 ]
[ERROR:0@0.113] global /io/opencv/modules/dnn/src/net_impl.cpp (1184) getLayerShapesRecursively Exception message: OpenCV(4.6.0) /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:404: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 4 in function 'getMemoryShapes'

Traceback (most recent call last):
  File "/usr/local/bin/deface", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/deface/deface.py", line 372, in main
    image_detect(
  File "/usr/local/lib/python3.10/dist-packages/deface/deface.py", line 187, in image_detect
    dets, _ = centerface(frame, threshold=threshold)
  File "/usr/local/lib/python3.10/dist-packages/deface/centerface.py", line 86, in __call__
    heatmap, scale, offset, lms = self.net.forward(self.onnx_output_names)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/dnn/src/layers/convolution_layer.cpp:404: error: (-2:Unspecified error) Number of input channels should be multiple of 3 but got 4 in function 'getMemoryShapes'
```

![friends](https://user-images.githubusercontent.com/1794222/210032037-79ad7d32-ce18-42c2-b725-1228596fc2d8.png)

**Comment by mdraw** [comment]
`deface` always expects RGB images. If you have RGBA images you can remove the alpha channel and then pass the image to `deface`.
If there is a need for automatic handling of non-RGB images inside `deface` itself, we can add an automatic conversion step here: https://github.com/ORB-HD/deface/blob/master/deface/centerface.py#L73

**Comment by SlausB** [comment]
@mdraw Thank you for your answer! I think adding auto conversion under-the-hood would be cool! Allowing `deface` working with more images by default.
Should I prepare a pull request? It would take some time for me to figure out how things work in `deface` though ...

**Comment by mdraw** [comment]
I have just added an automatic conversion feature for RGBA and grayscale inputs. Outputs are not converted back but are always in RGB. Your test image now works for me. Can you please confirm that with the newest commit?

**Comment by SlausB** [comment]
@mdraw  It worked now, thank you!
