### ISSUE TITLE
cv2.error: OpenCV 

### ISSUE THREAD

**Issue by Tralapo** [ORB-HD/deface#33]
Hi, I've been using this tool for quite a while now, thanks!

I upgraded my server to Ubuntu 22.04 today and it started failing after that. I'm not an expert in Pyhton, so having trouble debugging.
I did try to delete and then install the deface packages again, this does not seem to have any effect.

This is whats happening:

```
root@server:[/home/user] deface 21.jpg
Input:  21.jpg
Output: 21_anonymized.jpg
Traceback (most recent call last):
  File "/usr/local/bin/deface", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/deface/deface.py", line 368, in main
    image_detect(
  File "/usr/local/lib/python3.10/dist-packages/deface/deface.py", line 183, in image_detect
    dets, _ = centerface(frame, threshold=threshold)
  File "/usr/local/lib/python3.10/dist-packages/deface/centerface.py", line 86, in __call__
    heatmap, scale, offset, lms = self.net.forward(self.onnx_output_names)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/layers/fast_convolution/winograd_3x3s1_f63.cpp:147: error: (-215:Assertion failed) _FX_WINO_IBLOCK == 3 && _FX_WINO_KBLOCK == 4 in function '_fx_winograd_accum_f32'

munmap_chunk(): invalid pointer
```

**Comment by mdraw** [comment]
This looks like an error inside of OpenCV itself. Have you tried different versions of OpenCV? You can also avoid the OpenCV convolution code path by installing onnx-runtime and using that as the backend (see https://github.com/ORB-HD/deface/blob/master/README.md#hardware-acceleration).

**Comment by Tralapo** [comment]
I was just trying again, this time with a completely fresh Ubuntu 22.04.01 LTS installation with nothing else installed.

It won't work either, but with a different error:

```
root@DESKTOP:~$ deface city.jpg
Traceback (most recent call last):
  File "/usr/local/bin/deface", line 5, in <module>
    from deface.deface import main
  File "/usr/local/lib/python3.10/dist-packages/deface/deface.py", line 16, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by Tralapo** [comment]
Thank you for your time, I guess this is not really the right place for noob questions from me, haha.
Anyhow, I installed a fresh Ubuntu 22.04 again, first installed OpenCV manually with `sudo apt install python3-opencv` end then installed deface through pip. Now it runs without any errors.

Will try upgrading my actual server again and try the same route. Anyhow, thanks!

**Comment by mdraw** [comment]
No problem, glad to hear that it works now with the apt installation. Good luck with the server upgrade!
