### ISSUE TITLE
executing in windows cmd

### ISSUE THREAD

**Issue by fersegundo2** [ORB-HD/deface#58]
I have limited technical knowledge

I installed correctly in a cmd in windows (I run it as admin)

after that "deface" is not ricognized as a command. Maybe its as easy as setting some directory to PATH (or alternatively typing the whole path to where it is).

I tried "pip where deface" ... says its not there

I know it was installed to: "C:\users\fernando\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages\deface"

I tried getting into this directory and typing "deface". It also does not find it

then I tried " python3 deface.py" this is the output:

PS C:\users\fernando\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages\deface> python3 deface.py D:\Downloads\villalba.mp4
Traceback (most recent call last):
  File "C:\users\fernando\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages\deface\deface.py", line 17, in <module>
    from deface import __version__
  File "C:\users\fernando\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages\deface\deface.py", line 17, in <module>
    from deface import __version__
ImportError: cannot import name '__version__' from partially initialized module 'deface' (most likely due to a circular import) (C:\users\fernando\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages\deface\deface.py)
PS C:\users\fernando\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages\deface>

I don't know what else to try. I will try to install a virtual ubuntu and try there, but it would be nice if there was a fool-proof way to easily use this tool in windows

Thank you for your efforts!

**Comment by StealUrKill** [comment]
What python are you using. Your directory looks way different than mine and the package works flawless.

**Comment by Dissociable** [comment]
@fersegundo2 You may be using pyenv, if so, execute `pyenv rehash` and you're good to go (`deface file.mp4`)

Also, I noticed that I need to install `rembg[gpu]` so deface can use the GPU without errors (`pip install rembg[gpu] onnx onnxruntime-gpu`)

@StealUrKill You may want to add `rembg[gpu]` to the readme file, thanks.

**Comment by StealUrKill** [comment]
> @fersegundo2 You may be using pyenv, if so, execute `pyenv rehash` and you're good to go (`deface file.mp4`)
> 
> Also, I noticed that I need to install `rembg[gpu]` so deface can use the GPU without errors (`pip install rembg[gpu] onnx onnxruntime-gpu`)
> 
> @StealUrKill You may want to add `rembg[gpu]` to the readme file, thanks.

I am not familiar with `rembg[gpu]`. Using pip install onnxruntime-gpu has worked fine for me.

And do you mean the readme on my forked version? I am not the original creator/maintainer for deface.
