### ISSUE TITLE
OSError: libcublas.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by frankenstein91** [ORB-HD/deface#6]
Unfortunately, I can't use the extended processing power of my GPU under Archlinux. I have installed CUDA10 for testing, default is already CUDA11 here. @microsoft can you help with onnxruntime?

```
% deface --backend onnxrt --scale 1280x720 person1.mp4
Traceback (most recent call last):
  File "/home/USer/Videos/Walk/Projekt/videoPython/bin/deface", line 8, in <module>
    sys.exit(main())
  File "/home/USer/Videos/Walk/Projekt/videoPython/lib/python3.7/site-packages/deface/deface.py", line 277, in main
    centerface = CenterFace(in_shape=in_shape, backend=backend)
  File "/home/USer/Videos/Walk/Projekt/videoPython/lib/python3.7/site-packages/deface/centerface.py", line 38, in __init__
    import onnxruntime
  File "/home/USer/Videos/Walk/Projekt/videoPython/lib/python3.7/site-packages/onnxruntime/__init__.py", line 13, in <module>
    from onnxruntime.capi._pybind_state import get_all_providers, get_available_providers, get_device, set_seed, \
  File "/home/USer/Videos/Walk/Projekt/videoPython/lib/python3.7/site-packages/onnxruntime/capi/_pybind_state.py", line 9, in <module>
    import onnxruntime.capi._ld_preload  # noqa: F401
  File "/home/USer/Videos/Walk/Projekt/videoPython/lib/python3.7/site-packages/onnxruntime/capi/_ld_preload.py", line 12, in <module>
    _libcublas = CDLL("libcublas.so.10", mode=RTLD_GLOBAL)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcublas.so.10: cannot open shared object file: No such file or directory
deface --backend onnxrt --scale 1280x720 person1.mp4  1,37s user 3,96s system 1231% cpu 0,433 total

```
cycler==0.10.0
decorator==4.4.2
deface==1.0.0
imageio==2.9.0
imageio-ffmpeg==0.4.2
kiwisolver==1.3.1
matplotlib==3.3.3
networkx==2.5
numpy==1.19.4
onnx==1.8.0
onnxruntime-gpu==1.6.0
opencv-python==4.4.0.46
Pillow==8.0.1
protobuf==3.14.0
pyparsing==2.4.7
python-dateutil==2.8.1
PyWavelets==1.1.1
scikit-image==0.18.0
scipy==1.5.4
six==1.15.0
tifffile==2020.12.8
tqdm==4.54.1
typing-extensions==3.7.4.3

**Comment by mdraw** [comment]
Sorry for the late reply. This seems to be a common [CUDA installation issue](https://stackoverflow.com/questions/55224016/importerror-libcublas-so-10-0-cannot-open-shared-object-file-no-such-file-or) and is not related to deface.
